/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.ticket.jooq.tables;


import de.crafted.api.service.ticket.jooq.DefaultSchema;
import de.crafted.api.service.ticket.jooq.Keys;
import de.crafted.api.service.ticket.jooq.tables.records.TicketImageRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketImage extends TableImpl<TicketImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ticket_image</code>
     */
    public static final TicketImage TICKET_IMAGE = new TicketImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketImageRecord> getRecordType() {
        return TicketImageRecord.class;
    }

    /**
     * The column <code>ticket_image.ticket_id</code>.
     */
    public final TableField<TicketImageRecord, Long> TICKET_ID = createField(DSL.name("ticket_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ticket_image.image_id</code>.
     */
    public final TableField<TicketImageRecord, Long> IMAGE_ID = createField(DSL.name("image_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private TicketImage(Name alias, Table<TicketImageRecord> aliased) {
        this(alias, aliased, null);
    }

    private TicketImage(Name alias, Table<TicketImageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ticket_image</code> table reference
     */
    public TicketImage(String alias) {
        this(DSL.name(alias), TICKET_IMAGE);
    }

    /**
     * Create an aliased <code>ticket_image</code> table reference
     */
    public TicketImage(Name alias) {
        this(alias, TICKET_IMAGE);
    }

    /**
     * Create a <code>ticket_image</code> table reference
     */
    public TicketImage() {
        this(DSL.name("ticket_image"), null);
    }

    public <O extends Record> TicketImage(Table<O> child, ForeignKey<O, TicketImageRecord> key) {
        super(child, key, TICKET_IMAGE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TicketImageRecord> getPrimaryKey() {
        return Keys.TICKET_IMAGE_PKEY;
    }

    @Override
    public List<UniqueKey<TicketImageRecord>> getKeys() {
        return Arrays.<UniqueKey<TicketImageRecord>>asList(Keys.TICKET_IMAGE_PKEY);
    }

    @Override
    public List<ForeignKey<TicketImageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TicketImageRecord, ?>>asList(Keys.TICKET_IMAGE__TICKET_IMAGE_TICKET_ID_FKEY);
    }

    private transient Ticket _ticket;

    public Ticket ticket() {
        if (_ticket == null)
            _ticket = new Ticket(this, Keys.TICKET_IMAGE__TICKET_IMAGE_TICKET_ID_FKEY);

        return _ticket;
    }

    @Override
    public TicketImage as(String alias) {
        return new TicketImage(DSL.name(alias), this);
    }

    @Override
    public TicketImage as(Name alias) {
        return new TicketImage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketImage rename(String name) {
        return new TicketImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketImage rename(Name name) {
        return new TicketImage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
