/*
 * This file is generated by jOOQ.
 */
package de.thb.craftsquad.service.ticket.jooq.tables.records;


import de.thb.craftsquad.service.ticket.jooq.tables.TicketTag;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketTagRecord extends UpdatableRecordImpl<TicketTagRecord> implements Record2<Long, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ticket_tag.ticket_id</code>.
     */
    public void setTicketId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ticket_tag.ticket_id</code>.
     */
    public Long getTicketId() {
        return (Long) get(0);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setTag(Object value) {
        set(1, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getTag() {
        return get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Object> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Object> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Object> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TicketTag.TICKET_TAG.TICKET_ID;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field2() {
        return TicketTag.TICKET_TAG.TAG;
    }

    @Override
    public Long component1() {
        return getTicketId();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component2() {
        return getTag();
    }

    @Override
    public Long value1() {
        return getTicketId();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value2() {
        return getTag();
    }

    @Override
    public TicketTagRecord value1(Long value) {
        setTicketId(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public TicketTagRecord value2(Object value) {
        setTag(value);
        return this;
    }

    @Override
    public TicketTagRecord values(Long value1, Object value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketTagRecord
     */
    public TicketTagRecord() {
        super(TicketTag.TICKET_TAG);
    }

    /**
     * Create a detached, initialised TicketTagRecord
     */
    public TicketTagRecord(Long ticketId, Object tag) {
        super(TicketTag.TICKET_TAG);

        setTicketId(ticketId);
        setTag(tag);
    }
}
