/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.image.jooq.tables.records;


import de.crafted.api.service.image.jooq.tables.Image;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageRecord extends UpdatableRecordImpl<ImageRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>image.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>image.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>image.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>image.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>image.alt_text</code>.
     */
    public void setAltText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>image.alt_text</code>.
     */
    public String getAltText() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Image.IMAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Image.IMAGE.URL;
    }

    @Override
    public Field<String> field3() {
        return Image.IMAGE.ALT_TEXT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getAltText();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getAltText();
    }

    @Override
    public ImageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ImageRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ImageRecord value3(String value) {
        setAltText(value);
        return this;
    }

    @Override
    public ImageRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageRecord
     */
    public ImageRecord() {
        super(Image.IMAGE);
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(Long id, String url, String altText) {
        super(Image.IMAGE);

        setId(id);
        setUrl(url);
        setAltText(altText);
    }
}
