/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.account.jooq;


import de.crafted.api.service.account.jooq.tables.Account;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
