/*
 * This file is generated by jOOQ.
 */
package de.thb.craftsquad.service.ticket.jooq;


import de.thb.craftsquad.service.ticket.jooq.tables.Ticket;
import de.thb.craftsquad.service.ticket.jooq.tables.TicketImage;
import de.thb.craftsquad.service.ticket.jooq.tables.TicketTag;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>ticket_image</code>.
     */
    public static final TicketImage TICKET_IMAGE = TicketImage.TICKET_IMAGE;

    /**
     * The table <code>ticket_tag</code>.
     */
    public static final TicketTag TICKET_TAG = TicketTag.TICKET_TAG;
}
